### ISSUE TITLE
Products MVP

### ISSUE THREAD

**Issue by 93lykevin** [93lykevin/StreetX#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [ ] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by 93lykevin** [comment]
Products index and show pages have appropriate data.

**Comment by jenkennedy** [comment]
I think it's time for a Favicon to make your site look official! (Icon rendered in the browser tab)

### Products Index Page
- [ ] Reduce font size and add margin to top and bottom
![Screen Shot 2019-09-17 at 5 37 34 PM](https://user-images.githubusercontent.com/39272166/65093680-e7807c80-d971-11e9-9f35-471f002fecdf.png)
![Screen Shot 2019-09-17 at 5 38 12 PM](https://user-images.githubusercontent.com/39272166/65093855-f23b1180-d971-11e9-9c49-addbe8186322.png)
- [ ] Add margin above first row of items (between grey bar and start of index items)
![Screen Shot 2019-09-17 at 5 38 44 PM](https://user-images.githubusercontent.com/39272166/65094492-18f94800-d972-11e9-8df5-b75a26cf9ea3.png)
![Screen Shot 2019-09-17 at 5 39 18 PM](https://user-images.githubusercontent.com/39272166/65094536-1dbdfc00-d972-11e9-825b-33b6ee565dd7.png)
### Product Show Page
- [ ] Render details in a row instead of column to match stockX
![Screen Shot 2019-09-17 at 6 02 52 PM](https://user-images.githubusercontent.com/39272166/65095291-67f4ac80-d975-11e9-96fc-2c14885e94d2.png)
![Screen Shot 2019-09-17 at 6 02 52 PM](https://user-images.githubusercontent.com/39272166/65095303-6fb45100-d975-11e9-9e20-d2286b737244.png)
- [ ] center the "Related Products" items
![Screen Shot 2019-09-17 at 6 04 10 PM](https://user-images.githubusercontent.com/39272166/65095348-9b373b80-d975-11e9-8195-e87f6af20533.png)

**Comment by jenkennedy** [comment]
- [ ] change `/index` route to be `/` for now so that stuff renders when a user logs in.
